[tools]
ast-grep = "latest"
aws-cli = "latest"
bat = "latest"
carapace = "latest"
claude = "latest"
coursier = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
github-cli = "latest"
gitui = "latest"
go = "latest"
gron = "latest"
grpcurl = "latest"
helm = "latest"
hurl = "latest"
java = "21"
jc = "latest"
jj = "latest"
jless = "latest"
jq = "latest"
kubectl = "latest"
lazygit = "latest"
lsd = "latest"
mill = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
sd = "latest"
starship = "latest"
tfenv = "latest"
tree-sitter = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
yt-dlp = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []
